# Generated by Django 5.0.2 on 2026-03-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paquetes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('solucion', models.TextField(blank=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='paquetes.paquete')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
