# Generated by Django 5.0.2 on 2026-03-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
                'db_table': 'estatus',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Paqueteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paquetería',
                'verbose_name_plural': 'Paqueterías',
                'db_table': 'paqueterias',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('numero_guia', models.CharField(db_index=True, max_length=100, unique=True)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('fecha_registro', models.DateField()),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='accounts.cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_creados', to=settings.AUTH_USER_MODEL)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='paquetes.estatus')),
                ('paqueteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='paquetes.paqueteria')),
            ],
            options={
                'db_table': 'paquetes',
                'ordering': ['-fecha_registro', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='paquetes.paquete')),
            ],
            options={
                'db_table': 'historial_cambios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paquete',
            index=models.Index(fields=['numero_guia'], name='paquetes_numero__8b4667_idx'),
        ),
        migrations.AddIndex(
            model_name='paquete',
            index=models.Index(fields=['estatus', 'fecha_registro'], name='paquetes_estatus_470e37_idx'),
        ),
    ]
