# Generated by Django 5.0.2 on 2026-03-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archivo', models.FileField(upload_to='importaciones/%Y/%m/')),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_exitosas', models.IntegerField(default=0)),
                ('filas_error', models.IntegerField(default=0)),
                ('errores', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'importaciones_excel',
                'ordering': ['-created_at'],
            },
        ),
    ]
